### ISSUE TITLE
auto mode rules should be except container per tab not per origin

### ISSUE THREAD

**Issue by ivysrono** [igorlogius/open-in-temp-container#14]
**Describe the bug**

If one of the rules matched the origin/the main url of the tab so temp container is not applied to it, every other request from that origin should also without temp container.

However, it is not now.

**To Reproduce**
1. Enable auto mode and add `^https://www.apkmirror.com/.*` to rules.
2. Visit https://www.apkmirror.com/ .
3. After some redirector, the tab url will be `https://challenges.cloudflare.com/.+` with one temp container.

**Expected behavior**
Just as title.

**Desktop (please complete the following information):**
 - Version 1.1.20

**Comment by igorlogius** [comment]
Auto Mode is working as designed. The website is triggering a redirect from a un-containered tab and auto-mode is re-opening this tab with a non-whitelisted url into a new temporary container. 

I think, you can still do what you want, by just opening a temp container in advance.  

1. on the preference page, change the toolbar action to open a new empty temp container
1. click the toolbar button, to open a empty new temp container
2. visit  `https://www.apkmirror.com` in the temp container 

Since tabs, which are already opened in a temp container are ignored by auto-mode handling, you can use this, to open a temp container, that doenst care about further navigation and redirects. Everything will stay in one container.

**Comment by igorlogius** [comment]
I am really debatting in my head if auto-mode is such a good idea or even necessary, since firefox already has total cookie protection enabled aka. seperates cookies per site. There is not much of a point of using seperate containers for each url, except if you want to use mutliple logins at the same site or just want to visit a site, without any cookies. I suspect many people are unaware of this ... and might think container provide an addional level of security ... which they dont AFAIK. And this feature only seems to increase this misconception.

**Comment by igorlogius** [comment]
In that case i might just remove the feature, since it seems to have a higher potential to cause troubles with other addons then it's worth.

**Comment by igorlogius** [comment]
So i am not 100% convinced that it is worth to re-add the url-list.

**Comment by agitoxin** [comment]
Hi! I've just found the auto-mode is removed and seen this post.
I'm fan of this feature since I'd like to isolate my Google logins (e.g. gmail) and Google search.
I always search in temporary containers so that Google cannot (maybe) track me easily with logged-in searching page.
Not sure if you have any suggestion on this kind of scenario but auto-mode is convenient instead of manual open. And it does not harm keeping there. ;)

**Comment by igorlogius** [comment]
@agitoxin 
@ivysrono 

This is a common problem for all kinds of software 

https://xkcd.com/1172/

The question is how to best resolve this.

**Comment by agitoxin** [comment]
Well..IMO, a toggle to enable/disable for personalization is optimal. ;)

**Comment by igorlogius** [comment]
Ok, i'll re-add it, BUT i wont support or fix any kind of compatability issues with other container addons.
