### ISSUE TITLE
Delete browsing history

### ISSUE THREAD

**Issue by anewuser** [igorlogius/open-in-temp-container#2]
Hello. What do you think of adding an option to automatically clear your containerized browsing history when a temporary container is deleted? This would allow us to use temporary containers as a replacement for private windows.

**Comment by igorlogius** [comment]
Hi, 

That is actually something i took a look at quite a while back. 

i wanted to create a addon that did exactly what you describe, a "private container" (aka. one that doenst record history or at least destory it history) But sadly i had to discover that this was not as easily doable as i suspected it to be.  If i rember correctly that was mostly because there is no association between tabs and history elements in firefox that would allow any api to remove history elements after a serious of tabs with specific attributes (aka. container'ed) are closed. 

I even remember looking into why it is this way and i kind of went down a rabbit hole into mozillas bugtracker and some internal firefox code ... and the end i seems like there would need to be some major internal changes made to datastructures used by many other modules to acomplish this ... which did not look like something that would happen any time soon, so ... did not persue it further.

**Comment by anewuser** [comment]
Have you taken a look at how [Temporary Containers](https://github.com/stoically/temporary-containers) accomplishes this? Maybe you'd be able to copy or adapt the relevant code snippets:

https://github.com/stoically/temporary-containers/blob/main/src/background/history.ts

![Screenshot 2023-10-30 194423](https://github.com/igorlogius/open-in-temp-container/assets/6733770/6627d66a-0adb-4bd6-90ec-c784810d867c)


Unfortunately, its developer passed a way a while ago, and I'm afraid this extension will eventually stop working. That's why I found it nice that you've already developed a lightweight alternative.

**Comment by igorlogius** [comment]
The warning is more or less the reason why i did not include this feature, (It describes exactly the drawback of the disconnect i mentioned in my previous comment) 

If you really want to have a auto cleanup option like TC has, i think i could add even.

**Comment by igorlogius** [comment]
Thinking about this a little longer ... the IMO simplest and better way (that is also already available) to correctly handle history deletion would be to use a private window together with "open in temp container".

But it seems currently the addon doesnt work correctly in a private window , because the  cookieStore creation seems to fail ... i'll look into that and see what i can do.

**Comment by anewuser** [comment]
There's also a new, experimental solution: [No History Containers](https://addons.mozilla.org/firefox/addon/no-history-containers/). 

I understand that you prefer to keep your extensions as simple as possible. These are just suggestions, in case you or somebody else decide to implement this feature in the future.

**Comment by igorlogius** [comment]
History Prevention Feature added.

This feature is the closest i am able and willing to add, as long as there is no none-speculative way to link history items with containers or tabs. 

The way temporary containers handles seemed to be far to destructive, since one accidental navigation to a frequently visited site, can potentially completely delete the entrie history.  

closing this for now, but might revisit the topic in case something on the side of the history API might change.
